### ISSUE TITLE
No ads

### ISSUE THREAD

**Issue by ndubbaka** [Pragament/flutter_news_browser_app#1]
adblocker integration & support

https://hindi.oneindia.com/news/international/over-24-000-indian-americans-to-attend-modi-us-event-in-new-york-011-1089153.html

https://telugu.hindustantimes.com/telangana/union-minister-bandi-sanjay-sensational-comments-on-hydra-121725002758686.html

**Comment by SayedZeeshanHyder** [comment]
I'll want to work on this Issue
